name: Sistema Runner CI

on:
  push:
    branches: [ "main" ] # Garante que roda a cada push na branch principal
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Multiplataforma
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Define as 3 plataformas exigidas no requisito
        goos: [linux, windows, darwin]
        goarch: [amd64]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        BINARY_NAME=assinatura-${{ matrix.goos }}-${{ matrix.goarch }}
        if [ "${{ matrix.goos }}" = "windows" ]; then BINARY_NAME=$BINARY_NAME.exe; fi
        
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o build/$BINARY_NAME ./cmd/assinatura

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binários-${{ matrix.goos }}
        path: build/