# Porta padrão do servidor HTTP.
# Pode ser sobrescrita via: --server.port=XXXX ou variável SERVER_PORT
server.port=8080

# Suprime logs do Spring Boot para não poluir o stdout no modo CLI
logging.level.root=OFF
logging.level.org.springframework=OFF
spring.main.banner-mode=off
