name: Sistema Runner CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-go-apps:
    name: Build CLIs Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        app: [cli-assinatura]
    
    steps:
    - uses: actions/checkout@v4

    - name: Build Multiplataforma cli-assinatura
      working-directory: ./${{ matrix.app }}
      run: |
        mkdir -p ../build/cli-assinatura
        go mod tidy
        
        BINARY_NAME=${{ matrix.app }}-${{ matrix.goos }}-amd64
        if [ "${{ matrix.goos }}" = "windows" ]; then BINARY_NAME=$BINARY_NAME.exe; fi
        
        echo "Iniciando build de ${{ matrix.app }} para ${{ matrix.goos }}..."
        
        GOOS=${{ matrix.goos }} GOARCH=amd64 go build -o ../build/cli-assinatura/$BINARY_NAME ./cmd/assinatura/main.go

    - name: Upload Artifacts cli-assinatura
      uses: actions/upload-artifact@v4
      with:
        name: binarios-${{ matrix.app }}-${{ matrix.goos }}
        path: build/cli-assinatura/

    - name: Build Multiplataforma cli-simulador
      working-directory: ./${{ matrix.app }}
      run: |
        mkdir -p ../build/cli-simulador
        go mod tidy
        
        BINARY_NAME=${{ matrix.app }}-${{ matrix.goos }}-amd64
        if [ "${{ matrix.goos }}" = "windows" ]; then BINARY_NAME=$BINARY_NAME.exe; fi
        
        echo "Iniciando build de ${{ matrix.app }} para ${{ matrix.goos }}..."
        
        GOOS=${{ matrix.goos }} GOARCH=amd64 go build -o ../build/cli-simulador/$BINARY_NAME ./cmd/simulador/main.go

    - name: Upload Artifacts cli-simulador
      uses: actions/upload-artifact@v4
      with:
        name: binarios-${{ matrix.app }}-${{ matrix.goos }}
        path: build/cli-simulador/