name: Sistema Runner CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-go-apps:
    name: Build CLIs Go
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, windows, darwin]
        app: [cli-assinatura, cli-simulador]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22' 

    - name: Build Multiplataforma
      working-directory: ./${{ matrix.app }}
      run: |
        mkdir -p ../build/${{ matrix.app }}
      
        go mod tidy
        
        BINARY_NAME=${{ matrix.app }}-${{ matrix.goos }}-amd64
        if [ "${{ matrix.goos }}" = "windows" ]; then BINARY_NAME=$BINARY_NAME.exe; fi
        
        echo "Iniciando build de ${{ matrix.app }} para ${{ matrix.goos }}..."
        
        GOOS=${{ matrix.goos }} GOARCH=amd64 go build -o ../build/${{ matrix.app }}/$BINARY_NAME ./cmd/...

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.app }}-${{ matrix.goos }}
        path: build/${{ matrix.app }}/