name: Sistema Runner CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-go-apps:
    name: Build CLIs Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Plataformas exigidas
        goos: [linux, windows, darwin]
        app: [cli-assinatura]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build Multiplataforma
      # O working-directory faz o 'go build' rodar dentro da pasta da aplicação
      working-directory: ./${{ matrix.app }}
      run: |
        BINARY_NAME=${{ matrix.app }}-${{ matrix.goos }}-amd64
        if [ "${{ matrix.goos }}" = "windows" ]; then BINARY_NAME=$BINARY_NAME.exe; fi
        
        GOOS=${{ matrix.goos }} GOARCH=amd64 go build -o ../build/cli-assinatura/$BINARY_NAME ./cli-assinatura/cmd/assinatura/main.go || go build -o ../build/cli-assinatura/$BINARY_NAME .

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binarios-${{ matrix.app }}-${{ matrix.goos }}
        path: build/cli-assinatura/